---

  - name: Make sure mapserver config directory exists
    file: dest=/etc/mapserver mode=755 state=directory


# This command works when done by hand:
#    rsync --delay-updates -F --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --rsync-path="sudo rsync" --out-format='<<CHANGED>>%i %n%L' "/home/fliadmin/tmp/installdir/etc/mapserver/." "ansible@10.1.2.4:/etc/mapserver/."

  - name: rsync the config files and shapefiles
    become: no
    local_action: >
      command
      rsync
      --delay-updates -FF --compress --timeout=10 --delete-after
      --archive --no-owner --no-group
      --rsh 'ssh -o stricthostkeychecking=no'   
      --rsync-path 'sudo rsync'
      --out-format='<<CHANGED>>%i %n%L'
      {{ lookup('env','INSTALL_DIR') }}/etc/mapserver/.
      ansible@{{ inventory_hostname }}:/etc/mapserver/.

  - name: ensure apache is running (and enable it at boot)
    service: name=apache2 state=started enabled=yes


# Now, with ansible 2.0, the synchronize module is giving the same error described here. 
# https://groups.google.com/forum/#!topic/ansible-project/aC3WStjfoh4
#
#  - name: Install mapserver config files and shapefiles
#    synchronize: src={{ lookup('env','INSTALL_DIR') }}/etc/mapserver/. dest=/etc/mapserver/.
#
# WARNING - WITH SOME VERSIONS OF ANSIBLE, THE "/." AT THE END OF THE LINE
# IS LOST IF YOU USE THE "~".
#    synchronize: src=~/mapserver_osm_templates/. dest=/etc/mapserver/mapserver_osm_templates/.
# This causes the arguments to act like
#    synchronize: src=~/mapserver_osm_templates dest=/etc/mapserver/mapserver_osm_templates/.
# which behaves very differently!!!!




# After this role completes, the following should create a map tile
#  http://localhost/cgi-bin/mapserv
#  http://localhost/cgi-bin/mapserv?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=default&map=%2Fetc%2Fmapserver%2Fmapserver_osm_templates%2Fmap%2Fqsgeo.map&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&STYLES=&BBOX=-13775786.985667605%2C5009377.085697312%2C-13149614.849955441%2C5635549.221409475
