---
  - name: ensure apache is at the latest version
    apt: pkg={{ item }} state=latest
    with_items:
      - apache2
      - cgi-mapserver
      - php5-mapscript
      - ttf-unifont
      - proj-bin
      - libproj9
      - libproj-dev

  - name: Apache | Enable module | Enable $module
    command: a2enmod {{ item }} creates=/etc/apache2/mods-enabled/{{ item }}.load
    notify:
      - restart apache
    with_items:
      - cgid

  - name: write the apache config files
    template: src={{ item }} dest=/etc/apache2/sites-available/{{ item }}
    with_items:
      - 002-apache-mapserver.conf
    notify:
      - restart apache

  - name: Enable sites
    command: a2ensite {{ item }} creates=/etc/apache2/sites-enabled/{{ item }}
    notify:
      - restart apache
    with_items:
      - 002-apache-mapserver.conf

  - name: Make sure static html directories exist
    file: dest={{ item }} mode=755 state=directory
    with_items:
      - /var/www/mapserver

#  - name: Install test page for mapserver
#    template: src=mapserver/index.html dest=/var/www/mapserver/index.html mode=755

  - name: ensure apache is running
    service: name=apache2 state=started

  - name: Make sure mapserver config directory exists
    file: dest=/etc/mapserver/mapserver_osm_templates mode=755 state=directory

   # WARNING - WITH SOME VERSIONS OF ANSIBLE, THE "/." AT THE END OF THE LINE
   # IS LOST IF YOU USE THE "~".
   #    synchronize: src=~/mapserver_osm_templates/. dest=/etc/mapserver/mapserver_osm_templates/.
   # This causes the arguments to act like
   #    synchronize: src=~/mapserver_osm_templates dest=/etc/mapserver/mapserver_osm_templates/.
   # which behaves very differently!!!!

  - name: Install mapserver config files and shapefiles
    synchronize: src={{ lookup('env','HOME') }}/mapserver_osm_templates/. dest=/etc/mapserver/mapserver_osm_templates/.

  - name: "add geodb.fli to hosts file"
    lineinfile: dest=/etc/hosts regexp='.*geodb' line="127.0.0.1 geodb" state=present
    ## TODO - Don't hard code this to localhost - get ansible to find the real value



# After this role completes, the following should create a map tile
#  http://localhost/cgi-bin/mapserv
#  http://localhost/cgi-bin/mapserv?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=default&map=%2Fetc%2Fmapserver%2Fmapserver_osm_templates%2Fmap%2Fqsgeo.map&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&STYLES=&BBOX=-13775786.985667605%2C5009377.085697312%2C-13149614.849955441%2C5635549.221409475
