---
- name: install some packages needed by many servers
  apt: pkg={{ item }} state=latest
  with_items:
    - unzip
    - sysstat

- name: add ansible user
  user: name=ansible
        createhome=yes
        home=/home/ansible
        state=present
        generate_ssh_key=yes
        ssh_key_bits=2048
        shell=/bin/bash

- name: add unprivileged 'gis' user
  user: name=gis
        createhome=yes
        home=/home/gis
        state=present
        generate_ssh_key=yes
        ssh_key_bits=2048
        shell=/bin/bash

- name: Set authorized key(s?) for user ansible
  vars:
    ansible_user_home: "{{ lookup('env','HOME') }}"
    ansible_user_key: "{{ lookup('file', ansible_user_home+'/.ssh/id_rsa.pub') }}"
  authorized_key: user=ansible key="{{ansible_user_key}}"

- name: configure sudoers
  lineinfile:
     dest: /etc/sudoers.d/ansible
     line: '{{ lookup("env","USER") }} ALL=(ALL) NOPASSWD: ALL'
     state: present
     create: yes
     regexp: '^{{ lookup("env","USER") }}'
     validate: 'visudo -cf %s'

- name: configure sudoers
  lineinfile:
     dest: /etc/sudoers.d/ansible
     line: 'ansible ALL=(ALL) NOPASSWD: ALL'
     state: present
     create: yes
     regexp: '^ansible'
     validate: 'visudo -cf %s'

- name: "Build hosts file"
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}}" state=present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: "{{groups['all']}}"
