---

  - name: Make sure static html directories exist
    file: dest={{ item }} mode=755 state=directory owner={{ lookup("env","USER") }}
    with_items:
      - /var/www/mapcache

  # Seems an ansible bug -- if I use 
  #    synchronize: src=roles/mapcache/files/var/www/test_maps/. dest=/var/www/mapcache/test_maps/.
  # the destination acts like /var/www/mapcache/test_maps/test_maps/.
  # 
  # - name: copy test pages for maps
  #   synchronize: src={{ lookup('pipe','pwd') }}/roles/mapcache/files/var/www/test_maps/. dest=/var/www/mapcache/test_maps/.

  - name: Copy test pages for maps
    become: false
    synchronize: src={{ lookup('env','INSTALL_DIR') }}/var/www/mapcache/. dest=/var/www/mapcache/.

  - name: Creates mapcache config directory
    file: path=/etc/mapcache state=directory

  - name: Install mapcache config files to /etc/mapcache
    become: false
    synchronize: src={{ lookup('env','INSTALL_DIR') }}/etc/mapcache/. dest=/etc/mapcache/.
    notify:
      - restart apache

  #
  # On Azure,  we're making a symlink to their default large data disk
  # location, so this ansible task fails.
  #
  # TODO: see if there's a rule that says it's OK if this directory
  # is actually a symlink to a real directory.
  #
  #   - name: Make sure a mapcache cache directory exists
  #     file: path=/var/cache/mapcache state=directory owner=www-data

  - name: Check old map cache tiles
    shell: ls -1 /var/cache/mapcache/
    register: cache_contents

  - name: Tell user to remove old map cache tiles
    debug: msg="consider removing /var/cache/mapcache/{{ item }}"
    with_items: '{{cache_contents.stdout_lines}}'

#  - name: Remove old map cache tiles
#    file: name=/var/cache/mapcache/{{ item }} state=absent
#    with_items: '{{cache_contents.stdout_lines}}'
#    notify:
#      - restart apache

# WARNING - WITH SOME VERSIONS OF ANSIBLE, THE "/." AT THE END OF THE LINE
# IS LOST IF YOU USE THE "~".
#    synchronize: src=~/certs/etc/ssl/moga/. dest=/etc/ssl/moga/.
# This causes the arguments to act like
#    synchronize: src=~/certs/etc/ssl/moga dest=/etc/ssl/moga/.
# which behaves very differently!!!!

