---
- name: Common for all machines
  hosts: ansible_managed
  become: yes
  roles:
    - ansible_managed

- name: MapCache hosts (apache, mod-tilecache, mod-proxy, etc)
  hosts: mapcache
  become: yes
  roles:
    - mapcache_software

- name: Set up mapserver application servers
  hosts: mapserver
  become: yes
  roles:
    - mapserver_software

- name: Install current postgres from the postgres repositories
  hosts: postgis-master
  become: yes
  vars:
     database_password: "changeme"
  roles:
    - postgres


# 
# At this point, the following script seems to work.
# 
#  env PGHOST=localhost bash install_spatial_db  --map-data=tiny

#  http://192.168.0.119:10080/cgi-bin/mapserv?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=default&map=%2Fetc%2Fmapserver%2Fmapserver_osm_templates%2Fmap%2Fqsgeo_subtlecolor.map&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&STYLES=&BBOX=-13775786.985667605%2C5009377.085697312%2C-13149614.849955441%2C5635549.221409475


#    - postgis-master
#
#- name: Install current postgres from the postgres repositories
#  hosts: postgis-slave
#  become: yes
#  roles:
#    - postgres
#    - postgis-slave

# At this point this should work: 
#  sudo -u postgres psql


